name: Build for aarch64-unknown-linux-gnu

# Triggered by push from cronjob.
# json_diff, 0.1.2, aarch64-unknown-linux-gnu, main and ubuntu-20.04 are replaced using sed.
# Title of job in https://github.com/cargo-bins/cargo-quickinstall/actions
# is set by the commit message, which is created by trigger-package-build.sh
on:
  push:
    branches:
      - trigger/aarch64-unknown-linux-gnu

jobs:
  build-popular-package:
    name: Build
    runs-on: ubuntu-20.04
    permissions: {}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout trigger commit
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          path: trigger
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: main
          path: cargo-quickinstall

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-auditable

      - name: build package
        env:
          TEMPDIR: ${{github.workspace}}/built.d
        run: |
          set -euxo pipefail
          # `tar` does not understand mixed forward and backslashes, but mkdir does.
          # Try coercing it into a single style?
          mkdir -p "$TEMPDIR"
          pushd "$TEMPDIR"
          TEMPDIR="$PWD"
          popd

          export CRATE=json_diff
          export TARGET_ARCH=aarch64-unknown-linux-gnu
          export VERSION=0.1.2

          cargo-quickinstall/build-version.sh "${CRATE}"
          touch $TEMPDIR/dummy-file
          ls $TEMPDIR
      # At this point, I don't think that you can really trust anything on the system anymore.
      # I'm not sure whether the js actions runtime is also affected by this.
      # TODO: try breaking things so that uploads don't work.

      - name: Upload run-local binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-ubuntu-20.04
          path: ${{github.workspace}}/built.d
          if-no-files-found: error

  upload-popular-package:
    name: Upload
    needs: build-popular-package
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout trigger commit
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.CRONJOB_DEPLOY_KEY }}
          persist-credentials: true
          path: trigger
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          # TODO: maybe this should be main or configurable or something?
          ref: main
          path: cargo-quickinstall

      - name: Download binary artifact
        uses: actions/download-artifact@v3
        with:
          name: built-ubuntu-20.04
          # TODO: check that we it can't write anywhere other than built.d
          path: ${{github.workspace}}/built.d

      - name: Check if tarball exists
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: ${{github.workspace}}/built.d/json_diff-0.1.2-aarch64-unknown-linux-gnu.tar.gz

      - name: Cancel if no tarball
        if: steps.check_files.outputs.files_exists == 'false'
        uses: andymckay/cancel-action@0.3

      - name: Wait for cancellation signal if no tarball
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          sleep 1m
          exit 1

      - name: Tag release
        run: |
          (
            cd trigger
            git tag json_diff-0.1.2-aarch64-unknown-linux-gnu
            git push origin json_diff-0.1.2-aarch64-unknown-linux-gnu
          )

      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: json_diff-0.1.2-aarch64-unknown-linux-gnu
          files: |
            ${{github.workspace}}/built.d/json_diff-0.1.2-aarch64-unknown-linux-gnu.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
